export enum ErrorType {
  UserNotFound = 'UserNotFound',
  UserNotCreated = 'UserNotCreated',
  TeacherNotFound = 'TeacherNotFound',
  TeacherNotCreated = 'TeacherNotCreated',
  StudentNotFound = 'StudentNotFound',
  StudentNotCreated = 'StudentNotCreated',
  StudentUpdateFailed = 'StudentUpdateFailed',
  ContactNotFound = 'ContactNotFound',
  ContactUpdateFailed = 'ContactUpdateFailed',
  EventNotCreated = 'EventNotCreated',
  EventUpdateFailed = 'EventUpdateFailed',
  LessonNotFound = 'LessonNotFound',
  LessonNotCreated = 'LessonNotCreated',
  LessonUpdateFailed = 'LessonUpdateFailed',
  LessonDeleteFailed = 'LessonDeleteFailed',
  CreditNotFound = 'CreditNotFound',
  InvalidOrMissingPaymentInformation = 'InvalidOrMissingPaymentInformation',
  InvalidGrade = 'InvalidGrade',
  AccountNotFound = 'AccountNotFound',
  AccountNotCreated = 'AccountNotCreated',
  PaymentAccountNotFound = 'PaymentAccountNotFound',
  PaymentFailed = 'PaymentFailed',
  PaymentUpdateFailed = 'PaymentUpdateFailed',
  PaymentDeleteFailed = 'PaymentDeleteFailed',
  Other = 'Other'
}
